"""memo generator image

Revision ID: d7831b2d8867
Revises: 765ade65749b
Create Date: 2023-07-13 10:53:18.430364

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd7831b2d8867'
down_revision = '765ade65749b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memogenerator',
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memogenerator_created_on'), 'memogenerator', ['created_on'], unique=False)
    op.create_index(op.f('ix_memogenerator_file'), 'memogenerator', ['file'], unique=False)
    op.create_index(op.f('ix_memogenerator_id'), 'memogenerator', ['id'], unique=False)
    op.create_index(op.f('ix_memogenerator_is_active'), 'memogenerator', ['is_active'], unique=False)
    op.create_index(op.f('ix_memogenerator_name'), 'memogenerator', ['name'], unique=False)
    # op.alter_column('customers', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_memogenerator_name'), table_name='memogenerator')
    op.drop_index(op.f('ix_memogenerator_is_active'), table_name='memogenerator')
    op.drop_index(op.f('ix_memogenerator_id'), table_name='memogenerator')
    op.drop_index(op.f('ix_memogenerator_file'), table_name='memogenerator')
    op.drop_index(op.f('ix_memogenerator_created_on'), table_name='memogenerator')
    op.drop_table('memogenerator')
    # ### end Alembic commands ###
